#!/bin/bash

echo -e "\033[31mInstallation du programme...\033[0m"

cd ./Client && make && cd ../server_lib && make

if test $? == 0
then
  echo -e "\033[31mProgramme installé !\033[0m"
else
  echo -e "\033[31mErreur a l'installation !\033[0m"
fi
